SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
# Game states
MENU = 0
PLAYING = 1
GAME_OVER = 2
SETTINGS = 3
SHOP = 4
PLAYER_RADIUS = 20
PLAYER_STARTING_LIVES = 3
PLAYER_MAX_LIVES = 5
LINE_WIDTH = 2 # Line width for drawing shapes
PLAYER_TURN_SPEED = 150 # degrees per second
PLAYER_SPEED = 200 # pixels per second
PLAYER_BOOST_MULTIPLIER = 2.0
PLAYER_INVINCIBILITY_SECONDS = 1.5
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500 # pixels per second
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.7
POWERUP_RADIUS = 15
POWERUP_SPAWN_RATE_SECONDS = 6.0
POWERUP_LIFESPAN_SECONDS = 15.0
POWERUP_MIN_RADIUS = 15
POWERUP_EFFECT_DURATION_SECONDS = 12.0
POWERUP_RAPID_FIRE_MULTIPLIER = 3.0
POWERUP_KINDS = 1
SHIELD_AMOUNT = 1
PLAYER_SHIELD_CAPACITY = 3
SHIELD_LIFESPAN_SECONDS = 10.0
SHIELD_SPAWN_RATE_SECONDS = 20.0
# Screen shake
SHAKE_DURATION = 0.25
SHAKE_INTENSITY = 7
# Particles
PARTICLE_COUNT = 8
PARTICLE_SPEED_MIN = 50
PARTICLE_SPEED_MAX = 150
PARTICLE_LIFESPAN = 0.4
# Homing shot
HOMING_TURN_RATE = 0.12
HOMING_LIFESPAN = 3.0
# Double shot
DOUBLE_SHOT_OFFSET = 8
# Homing explosion radii by level (index = level, level 1 = no explosion)
HOMING_EXPLOSION_RADII = [0, 0, 30, 50, 70, 100]
