[project]
name = "astroids"
version = "0.1.0"
description = "An asteroid game"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame==2.6.1",
]
[tool.uv]
package = true

[tool.setuptools]
py-modules = ["main", "asteroid", "asteroidfield", "circleshape", "constants", "laser", "logger", "player", "powerup", "progress", "score_manager", "settings_screen", "shield", "shop_screen", "shot"]

[project.scripts]
astroids = "main:main"
